# Generated by Django 4.2.6 on 2024-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontak',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_dua',
            field=models.ImageField(null=True, upload_to='gambar/banner', verbose_name='Baner 2 (575 x 200 px)'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_satu',
            field=models.ImageField(null=True, upload_to='gambar/banner', verbose_name='Baner 1 (575 x 200 px)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
    ]
