# Generated by Django 4.2.6 on 2024-06-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_kontak_map_alter_kategori_banner_dua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontak',
            name='map',
        ),
    ]
