# Generated by Django 4.2.6 on 2024-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_kontak_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='statis',
            name='map',
            field=models.TextField(null=True),
        ),
    ]
