# Generated by Django 4.2.6 on 2024-06-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_produk_gambar_lima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontak',
            old_name='no_whatsup',
            new_name='telpon',
        ),
    ]
