# Generated by Django 4.2.6 on 2024-06-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_subject_kontak_subjek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='dibeli',
        ),
    ]
