# Generated by Django 5.0.6 on 2024-07-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_chatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='statis',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statis',
            name='jam_kerja',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statis',
            name='whatsapp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
