# Generated by Django 5.0.6 on 2024-07-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_statis_jam_kerja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statis',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='statis',
            name='jam_kerja',
        ),
        migrations.RemoveField(
            model_name='statis',
            name='whatsapp',
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('wa', models.CharField(max_length=200, null=True, verbose_name='No Whatsapp')),
                ('alamat', models.TextField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Custumer',
            },
        ),
    ]
