# Generated by Django 5.0.6 on 2024-07-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_detailtransaksi_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='whatsapp',
            new_name='telpon',
        ),
    ]
