# Generated by Django 5.0.6 on 2024-07-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_whatsapp_transaksi_telpon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='telpon',
            new_name='whatsapp',
        ),
    ]
